name: u_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: any
  introduction_screen: ^3.0.2
  carousel_slider: any
  shared_preferences: ^2.2.0
  get: 4.6.5
  flutter: 
    sdk: flutter
  lottie: ^2.5.0

dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/gifs/
    - assets/animations/
    - assets/images/
    - assets/fonts/
    - assets/icons/

